language: csharp
sudo: required
dist: trusty

dotnet: 2.0.3
mono:
  - 5.4.1
  - latest # => "stable release"
os:
  - linux

addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

script:
  - ./build.sh

matrix:
  fast_finish: true
  allow_failures:
    - mono: latest
